[project]
name = "conformal-data-cleaning"
version = "0.1.0"
description = "TODO"
readme = "README.md"
authors = [
    { name = "Sebastian Jäger", email = "git@sebastian-jaeger.me" },
]
requires-python = ">=3.9,<3.13"
dependencies = [
    "autogluon-tabular>=1.4.0",
    "ipykernel>=6.31.0",
    "numpy>=2.0.2",
    "pandas>=2.3.3",
    "tab-err>=0.2.0",
    "typing-extensions>=4.15.0",
    "typer-slim>=0.20.0",
    "openml>=0.15.1",
]

[project.scripts]
conformal-data-cleaning = "conformal_data_cleaning:main"

[build-system]
requires = ["uv_build>=0.9.16,<0.10.0"]
build-backend = "uv_build"

[tool.ruff]
line-length = 160
target-version = "py39"
fix = true
extend-include = ["*.ipynb"]

[tool.ruff.lint]
select = [
    "ALL", # Include all the rules, including new ones
]
ignore = [
    "FIX", # Temporary developer notes should not break actions
    "COM812", # For compatibility with ruff-format
    "ISC001", # For compatibility with ruff-format
    "S311", # We do not require cryptographically-sound randomness
    "D100", # Do not document public modules
    "D104", # Do not document public packages
    "TD003", # Allow TODOs without links
    "ISC003", # Do not implicietly concatenate strings
    "S101", # Allow testing methods
]

[tool.ruff.lint.per-file-ignores]
"**/__init__.py" = [
    "F401", # Unused imports in __init__ files can make sense
]

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ty.environment]
python-version = "3.9"

[dependency-groups]
dev = [
    "ruff>=0.14.8",
    "ty>=0.0.1a32",
]
